### ISSUE TITLE
Add some content to the readme.

### ISSUE THREAD

**Issue by SapneshNaik** [SapneshNaik/GitCommits-demo#1]
# h1 Heading 8-)
## Horizontal Rules

___

---

***

## Typographic replacements

Enable typographer option to see result.

(c) (C) (r) (R) (tm) (TM) (p) (P) +-

test.. test... test..... test?..... test!....

!!!!!! ???? ,,  -- ---

"Smartypants, double quotes" and 'single quotes'

## Emphasis

**This is bold text**

__This is bold text__

*This is italic text*

_This is italic text_

~~Strikethrough~~

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue now has a bounty of $50.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/add-some-content-to-the-readme).
- Questions? Checkout [GitCommits Help](https://sandbox.gitcommits.com/faq)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. Open 2. **Started**  3. Submitted 4. Done

<hr>

**Work has been started.**

**<a href='https://sandbox.app.gitcommits.com/profile/cont1'>cont1</a> has been approved to start work.**

<hr />

**Message:** Approved


<a href='https://sandbox.app.gitcommits.com/issue/add-some-content-to-the-readme'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
### Additional Funds added to the bounty:
Additional fund of $50.00 has been added by <a href="https://sandbox.app.gitcommits.com/profile/funder2">funder2</a>
Co-Funder Message: I would like to support this issue

**Comment by angelleye-gitcommits** [comment]
### Additional Funds added to the bounty:
Additional fund of $60.00 has been added by <a href="https://sandbox.app.gitcommits.com/profile/sb-aqaj44101099">sb-aqaj44101099</a>
Co-Funder Message: I signed up just to support this ticket!

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/cont1'>cont1</a> Work has been approved by <a href='https://sandbox.app.gitcommits.com/profile/funder1'>funder1</a>.**
<hr />

**Message:** Pull request has been approved, you will receive the payment shortly.


<a href='https://sandbox.app.gitcommits.com/issue/add-some-content-to-the-readme'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
### Additional Funds added to the bounty:
Additional fund of $12.00 has been added by <a href="https://sandbox.app.gitcommits.com/profile/dmauryatesting">dmauryatesting</a>
Co-Funder Message: Another funding without logging in
