### ISSUE TITLE
Demo-26-Jan

### ISSUE THREAD

**Issue by SapneshNaik** [SapneshNaik/GitCommits-demo#3]
### Curabitur non nulla sit amet nisl tempus

```
 convallis quis ac lectus. Vivamus suscipit tortor eget felis porttitor volutpat. Curabitur non nulla sit amet nisl tempus convallis quis ac lectus.

Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem. Pellentesque in ipsum id orci porta dapibus.
```

_Praesent sapien massa, convallis a pellentesque nec, egestas non nisi. Quisque velit nisi, pretium ut lacinia in, elementum id enim. Curabitur aliquet quam id dui posuere blandit._

**Nulla quis lorem ut libero malesuada feugiat. Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec velit neque, auctor sit amet aliquam vel, ullamcorper sit amet ligula.**

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done

<hr>

**This issue now has a bounty of $150.00 attached to it.**

- If you would like to work on this issue you can 'start work' [on the GitCommits Issue Details page](https://sandbox.app.gitcommits.com/issue/demo-26-jan).
- Questions? Checkout [GitCommits Help](https://sandbox.gitcommits.com/faq)
- More funded Bounties are available on the [GitCommits Issue Explorer](https://sandbox.app.gitcommits.com/explorer)

**Comment by angelleye-gitcommits** [comment]
### Additional Funds added to the bounty:
Additional fund of $100.00 has been added by <a href="https://sandbox.app.gitcommits.com/profile/jigahoc201">jigahoc201</a>
Co-Funder Message: I would like to support this issue!

**Comment by angelleye-gitcommits** [comment]
Issue Status: 1. Open 2. **Started**  3. Submitted 4. Done

<hr>

**Work has been started.**

**<a href='https://sandbox.app.gitcommits.com/profile/cont1'>cont1</a> has been approved to start work.**

<hr />

**Message:** Go ahead!


<a href='https://sandbox.app.gitcommits.com/issue/demo-26-jan'>Click Here to view more</a> on GitCommits Bounty detail page.

**Comment by angelleye-gitcommits** [comment]
### Additional Funds added to the bounty:
Additional fund of $60.00 has been added by <a href="https://sandbox.app.gitcommits.com/profile/funder2">funder2</a>
Co-Funder Message: I would like to get this done ASAP!

**Comment by angelleye-gitcommits** [comment]
**<a href='https://sandbox.app.gitcommits.com/profile/cont1'>cont1</a> Work has been approved by <a href='https://sandbox.app.gitcommits.com/profile/funder1'>funder1</a>.**
<hr />

**Message:** Pull request has been approved, you will receive the payment shortly.


<a href='https://sandbox.app.gitcommits.com/issue/demo-26-jan'>Click Here to view more</a> on GitCommits Bounty detail page.
